#############################################################################
# Makefile for building: PhotoShock.app/Contents/MacOS/PhotoShock
# Generated by qmake (3.1) (Qt 5.12.3)
# Project:  PhotoShock.pro
# Template: app
# Command: /Users/alessandrocerro/Qt/5.12.3/clang_64/bin/qmake -o Makefile PhotoShock.pro -spec macx-g++ CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/gcc
CXX           = /Library/Developer/CommandLineTools/usr/bin/g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/include/opencv -I/usr/local/include -I../../Qt/5.12.3/clang_64/lib/QtWidgets.framework/Headers -I../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers -I../../Qt/5.12.3/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode10.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode10.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AGL.framework/Headers/ -I. -I../../Qt/5.12.3/clang_64/mkspecs/macx-g++ -F/Users/alessandrocerro/Qt/5.12.3/clang_64/lib
QMAKE         = /Users/alessandrocerro/Qt/5.12.3/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/alessandrocerro/Qt/5.12.3/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/alessandrocerro/Qt/5.12.3/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = PhotoShock1.0.0
DISTDIR = /Users/alessandrocerro/Desktop/PhotoShock/.tmp/PhotoShock1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/g++
LFLAGS        = -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/alessandrocerro/Qt/5.12.3/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/alessandrocerro/Qt/5.12.3/clang_64/lib /usr/local/lib/libopencv_core.3.4.6.dylib /usr/local/lib/libopencv_highgui.3.4.6.dylib -L/usr/local/lib -lopencv_dnn -lopencv_ml -lopencv_objdetect -lopencv_shape -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_imgproc -lopencv_flann -lopencv_core -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = blur.cpp \
		controller.cpp \
		flipHorizontal.cpp \
		flipVertical.cpp \
		grayscale.cpp \
		hsl_process.cpp \
		imghandling.cpp \
		main.cpp \
		mainwindow.cpp \
		model.cpp \
		rgb_process.cpp \
		rotation.cpp \
		sepia.cpp \
		sharp.cpp moc_mainwindow.cpp
OBJECTS       = blur.o \
		controller.o \
		flipHorizontal.o \
		flipVertical.o \
		grayscale.o \
		hsl_process.o \
		imghandling.o \
		main.o \
		mainwindow.o \
		model.o \
		rgb_process.o \
		rotation.o \
		sepia.o \
		sharp.o \
		moc_mainwindow.o
DIST          = test/lib/library.json \
		../../Qt/5.12.3/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.12.3/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.12.3/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.12.3/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.12.3/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.12.3/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.12.3/clang_64/mkspecs/common/sanitize.conf \
		../../Qt/5.12.3/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.12.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.12.3/clang_64/mkspecs/common/g++-base.conf \
		../../Qt/5.12.3/clang_64/mkspecs/common/g++-macx.conf \
		../../Qt/5.12.3/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.12.3/clang_64/mkspecs/macx-g++/qmake.conf \
		../../Qt/5.12.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.12.3/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/toolchain.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/link_pkgconfig.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/qml_debug.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/mac/mac.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/uic.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/qmake_use.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/file_copies.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/lex.prf \
		PhotoShock.pro blur.h \
		controller.h \
		flipHorizontal.h \
		flipVertical.h \
		grayscale.h \
		hsl_process.h \
		imghandling.h \
		kernels.h \
		mainwindow.h \
		model.h \
		observer.h \
		process.h \
		rgb_process.h \
		rotation.h \
		sepia.h \
		sharp.h \
		subject.h blur.cpp \
		controller.cpp \
		flipHorizontal.cpp \
		flipVertical.cpp \
		grayscale.cpp \
		hsl_process.cpp \
		imghandling.cpp \
		main.cpp \
		mainwindow.cpp \
		model.cpp \
		rgb_process.cpp \
		rotation.cpp \
		sepia.cpp \
		sharp.cpp
QMAKE_TARGET  = PhotoShock
DESTDIR       = 
TARGET        = PhotoShock.app/Contents/MacOS/PhotoShock

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.14.4
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/alessandrocerro/Desktop/PhotoShock/PhotoShock.pro


include /Users/alessandrocerro/Qt/5.12.3/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

PhotoShock.app/Contents/MacOS/PhotoShock: ui_mainwindow.h $(OBJECTS)  
	@test -d PhotoShock.app/Contents/MacOS/ || mkdir -p PhotoShock.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: PhotoShock.pro ../../Qt/5.12.3/clang_64/mkspecs/macx-g++/qmake.conf ../../Qt/5.12.3/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.12.3/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.12.3/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.12.3/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.12.3/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.12.3/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.12.3/clang_64/mkspecs/common/sanitize.conf \
		../../Qt/5.12.3/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.12.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.12.3/clang_64/mkspecs/common/g++-base.conf \
		../../Qt/5.12.3/clang_64/mkspecs/common/g++-macx.conf \
		../../Qt/5.12.3/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.12.3/clang_64/mkspecs/macx-g++/qmake.conf \
		../../Qt/5.12.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.12.3/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/toolchain.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/link_pkgconfig.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/qml_debug.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/mac/mac.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/uic.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/qmake_use.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/file_copies.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/lex.prf \
		PhotoShock.pro \
		../../Qt/5.12.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/QtGui.prl \
		../../Qt/5.12.3/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile PhotoShock.pro -spec macx-g++ CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
../../Qt/5.12.3/clang_64/mkspecs/features/spec_pre.prf:
../../Qt/5.12.3/clang_64/mkspecs/qdevice.pri:
../../Qt/5.12.3/clang_64/mkspecs/features/device_config.prf:
../../Qt/5.12.3/clang_64/mkspecs/common/unix.conf:
../../Qt/5.12.3/clang_64/mkspecs/common/mac.conf:
../../Qt/5.12.3/clang_64/mkspecs/common/macx.conf:
../../Qt/5.12.3/clang_64/mkspecs/common/sanitize.conf:
../../Qt/5.12.3/clang_64/mkspecs/common/gcc-base.conf:
../../Qt/5.12.3/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt/5.12.3/clang_64/mkspecs/common/g++-base.conf:
../../Qt/5.12.3/clang_64/mkspecs/common/g++-macx.conf:
../../Qt/5.12.3/clang_64/mkspecs/qconfig.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/features/qt_functions.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/qt_config.prf:
../../Qt/5.12.3/clang_64/mkspecs/macx-g++/qmake.conf:
../../Qt/5.12.3/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt/5.12.3/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/toolchain.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/mac/toolchain.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/default_pre.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/resolve_config.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/default_post.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/link_pkgconfig.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/qml_debug.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/mac/mac.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/warn_on.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/qt.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/resources.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/moc.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/uic.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/unix/thread.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/qmake_use.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/file_copies.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/mac/rez.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/exceptions.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/yacc.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/lex.prf:
PhotoShock.pro:
../../Qt/5.12.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../Qt/5.12.3/clang_64/lib/QtGui.framework/QtGui.prl:
../../Qt/5.12.3/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile PhotoShock.pro -spec macx-g++ CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

PhotoShock.app/Contents/PkgInfo: 
	@test -d PhotoShock.app/Contents || mkdir -p PhotoShock.app/Contents
	@$(DEL_FILE) PhotoShock.app/Contents/PkgInfo
	@echo "APPL????" > PhotoShock.app/Contents/PkgInfo
PhotoShock.app/Contents/Resources/empty.lproj: 
	@test -d PhotoShock.app/Contents/Resources || mkdir -p PhotoShock.app/Contents/Resources
	@touch PhotoShock.app/Contents/Resources/empty.lproj
	
PhotoShock.app/Contents/Info.plist: 
	@test -d PhotoShock.app/Contents || mkdir -p PhotoShock.app/Contents
	@$(DEL_FILE) PhotoShock.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.PhotoShock,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.PhotoShock,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.12,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,PhotoShock,g" -e "s,@LIBRARY@,PhotoShock,g" -e "s,\$${EXECUTABLE_NAME},PhotoShock,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../../Qt/5.12.3/clang_64/mkspecs/macx-g++/Info.plist.app >PhotoShock.app/Contents/Info.plist

all: Makefile \
		PhotoShock.app/Contents/PkgInfo \
		PhotoShock.app/Contents/Resources/empty.lproj \
		PhotoShock.app/Contents/Info.plist PhotoShock.app/Contents/MacOS/PhotoShock

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../Qt/5.12.3/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents blur.h controller.h flipHorizontal.h flipVertical.h grayscale.h hsl_process.h imghandling.h kernels.h mainwindow.h model.h observer.h process.h rgb_process.h rotation.h sepia.h sharp.h subject.h $(DISTDIR)/
	$(COPY_FILE) --parents blur.cpp controller.cpp flipHorizontal.cpp flipVertical.cpp grayscale.cpp hsl_process.cpp imghandling.cpp main.cpp mainwindow.cpp model.cpp rgb_process.cpp rotation.cpp sepia.cpp sharp.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r PhotoShock.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode $(EXPORT__PRO_FILE_)

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../Qt/5.12.3/clang_64/mkspecs/features/data/dummy.cpp
	/Library/Developer/CommandLineTools/usr/bin/g++ -pipe -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wall -W -dM -E -o moc_predefs.h ../../Qt/5.12.3/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h \
		../../Qt/5.12.3/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt/5.12.3/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		ui_mainwindow.h \
		model.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/include/opencv2/core/cv_cpu_helper.h \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/vsx_utils.hpp \
		/usr/local/include/opencv2/core/check.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/core/ovx.hpp \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/imgproc.hpp \
		subject.h \
		observer.h \
		imghandling.h \
		../../Qt/5.12.3/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.12.3/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/QImage \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/qimage.h \
		controller.h \
		rgb_process.h \
		process.h \
		hsl_process.h \
		rotation.h \
		flipVertical.h \
		sepia.h \
		blur.h \
		kernels.h \
		sharp.h \
		grayscale.h \
		moc_predefs.h \
		../../Qt/5.12.3/clang_64/bin/moc
	/Users/alessandrocerro/Qt/5.12.3/clang_64/bin/moc $(DEFINES) --include /Users/alessandrocerro/Desktop/PhotoShock/moc_predefs.h -I/Users/alessandrocerro/Qt/5.12.3/clang_64/mkspecs/macx-g++ -I/Users/alessandrocerro/Desktop/PhotoShock -I/usr/local/include/opencv -I/usr/local/include -I/Users/alessandrocerro/Qt/5.12.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/alessandrocerro/Qt/5.12.3/clang_64/lib/QtGui.framework/Headers -I/Users/alessandrocerro/Qt/5.12.3/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/10.0.1/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -F/Users/alessandrocerro/Qt/5.12.3/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		../../Qt/5.12.3/clang_64/bin/uic
	/Users/alessandrocerro/Qt/5.12.3/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

blur.o: blur.cpp blur.h \
		kernels.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/include/opencv2/core/cv_cpu_helper.h \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/vsx_utils.hpp \
		/usr/local/include/opencv2/core/check.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/core/ovx.hpp \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/imgproc.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o blur.o blur.cpp

controller.o: controller.cpp controller.h \
		model.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/include/opencv2/core/cv_cpu_helper.h \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/vsx_utils.hpp \
		/usr/local/include/opencv2/core/check.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/core/ovx.hpp \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/imgproc.hpp \
		subject.h \
		observer.h \
		imghandling.h \
		../../Qt/5.12.3/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.12.3/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/QImage \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/qimage.h \
		rgb_process.h \
		process.h \
		hsl_process.h \
		rotation.h \
		flipVertical.h \
		sepia.h \
		blur.h \
		kernels.h \
		sharp.h \
		grayscale.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o controller.o controller.cpp

flipHorizontal.o: flipHorizontal.cpp flipHorizontal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o flipHorizontal.o flipHorizontal.cpp

flipVertical.o: flipVertical.cpp flipVertical.h \
		process.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/include/opencv2/core/cv_cpu_helper.h \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/vsx_utils.hpp \
		/usr/local/include/opencv2/core/check.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/core/ovx.hpp \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/imgproc.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o flipVertical.o flipVertical.cpp

grayscale.o: grayscale.cpp grayscale.h \
		process.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/include/opencv2/core/cv_cpu_helper.h \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/vsx_utils.hpp \
		/usr/local/include/opencv2/core/check.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/core/ovx.hpp \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/imgproc.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o grayscale.o grayscale.cpp

hsl_process.o: hsl_process.cpp hsl_process.h \
		process.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/include/opencv2/core/cv_cpu_helper.h \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/vsx_utils.hpp \
		/usr/local/include/opencv2/core/check.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/core/ovx.hpp \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/imgproc.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hsl_process.o hsl_process.cpp

imghandling.o: imghandling.cpp imghandling.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/include/opencv2/core/cv_cpu_helper.h \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/vsx_utils.hpp \
		/usr/local/include/opencv2/core/check.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/core/ovx.hpp \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/imgproc.hpp \
		../../Qt/5.12.3/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.12.3/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/QImage \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../Qt/5.12.3/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Qt/5.12.3/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imghandling.o imghandling.cpp

main.o: main.cpp mainwindow.h \
		../../Qt/5.12.3/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt/5.12.3/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		ui_mainwindow.h \
		model.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/include/opencv2/core/cv_cpu_helper.h \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/vsx_utils.hpp \
		/usr/local/include/opencv2/core/check.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/core/ovx.hpp \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/imgproc.hpp \
		subject.h \
		observer.h \
		imghandling.h \
		../../Qt/5.12.3/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.12.3/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/QImage \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/qimage.h \
		controller.h \
		rgb_process.h \
		process.h \
		hsl_process.h \
		rotation.h \
		flipVertical.h \
		sepia.h \
		blur.h \
		kernels.h \
		sharp.h \
		grayscale.h \
		../../Qt/5.12.3/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt/5.12.3/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../Qt/5.12.3/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt/5.12.3/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		ui_mainwindow.h \
		model.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/include/opencv2/core/cv_cpu_helper.h \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/vsx_utils.hpp \
		/usr/local/include/opencv2/core/check.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/core/ovx.hpp \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/imgproc.hpp \
		subject.h \
		observer.h \
		imghandling.h \
		../../Qt/5.12.3/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.12.3/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/QImage \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/qimage.h \
		controller.h \
		rgb_process.h \
		process.h \
		hsl_process.h \
		rotation.h \
		flipVertical.h \
		sepia.h \
		blur.h \
		kernels.h \
		sharp.h \
		grayscale.h \
		../../Qt/5.12.3/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../../Qt/5.12.3/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

model.o: model.cpp model.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/include/opencv2/core/cv_cpu_helper.h \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/vsx_utils.hpp \
		/usr/local/include/opencv2/core/check.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/core/ovx.hpp \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/imgproc.hpp \
		subject.h \
		observer.h \
		imghandling.h \
		../../Qt/5.12.3/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.12.3/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/QImage \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/qimage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o model.o model.cpp

rgb_process.o: rgb_process.cpp rgb_process.h \
		process.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/include/opencv2/core/cv_cpu_helper.h \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/vsx_utils.hpp \
		/usr/local/include/opencv2/core/check.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/core/ovx.hpp \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/imgproc.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rgb_process.o rgb_process.cpp

rotation.o: rotation.cpp rotation.h \
		process.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/include/opencv2/core/cv_cpu_helper.h \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/vsx_utils.hpp \
		/usr/local/include/opencv2/core/check.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/core/ovx.hpp \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/imgproc.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rotation.o rotation.cpp

sepia.o: sepia.cpp sepia.h \
		process.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/include/opencv2/core/cv_cpu_helper.h \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/vsx_utils.hpp \
		/usr/local/include/opencv2/core/check.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/core/ovx.hpp \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/imgproc.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sepia.o sepia.cpp

sharp.o: sharp.cpp sharp.h \
		kernels.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/include/opencv2/core/cv_cpu_helper.h \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/vsx_utils.hpp \
		/usr/local/include/opencv2/core/check.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/core/ovx.hpp \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/imgproc.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sharp.o sharp.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/PhotoShock/bin || mkdir -p $(INSTALL_ROOT)/opt/PhotoShock/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/PhotoShock/bin/PhotoShock.app
	
	-$(QINSTALL) PhotoShock.app $(INSTALL_ROOT)/opt/PhotoShock/bin/PhotoShock.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/PhotoShock/bin/PhotoShock.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/PhotoShock/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

